name: docker-image

on:
  push:
    branches: [ "main" ]
    paths: ["Dockerfile",".github/workflows/docker-image.yaml"]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Docker tags and credentials for DockerHub Containers, customize!
    env:
      IMAGE_NAME: download-from-docker-hub
      IMAGE_VERSION: latest
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v3
    - name: Build and tag the image
      run: |
        docker build . --build-arg URL=${{ secrets.URL }} \
        --tag $DOCKER_USER/$IMAGE_NAME:$IMAGE_VERSION
    - name: Publish to DockerHub
      if: env.DOCKER_PASSWORD != ''
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        docker push $DOCKER_USER/$IMAGE_NAME:$IMAGE_VERSION
    - name: Login to ghcr.io
      uses: docker/login-action@v3.0.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Build and push (GHCR)
      id: docker_build2
      uses: docker/build-push-action@v5.1.0
      with:
        push: true
        platforms: linux/arm64,linux/amd64
        tags: ghcr.io/${{ github.actor }}/$IMAGE_NAME:$IMAGE_VERSION
        file: Dockerfile