name: docker-image

# on:
  # push:
  #   branches: [ "main" ]
  #   paths: ["Dockerfile",".github/workflows/docker-image.yaml"]
  # workflow_dispatch:
on:
  release:
    types:
      - created

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    # Docker tags and credentials for DockerHub Containers, customize!
    env:
      IMAGE_NAME: download-from-docker-hub
      IMAGE_VERSION: latest
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_PASSWORD }}
    - name: Build and push (Docker Hub)
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/arm64,linux/amd64
        tags: ${{ env.DOCKER_USER }}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}
        file: Dockerfile
        build-args: |
          URL: ${{ secrets.URL }}

    - name: Login to ghcr.io
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_ACCESS_TOKEN }}
    - name: Build and push (GHCR)
      id: docker_build2
      uses: docker/build-push-action@v5
      with:
        push: true
        platforms: linux/arm64,linux/amd64
        tags: ghcr.io/${{ github.actor }}/${{env.IMAGE_NAME}}:${{env.IMAGE_VERSION}}
        file: Dockerfile
        build-args: |
          URL: ${{ secrets.URL }}
